# Generated by Django 5.1.6 on 2025-02-23 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_delete_property'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=255)),
                ('phone_number', models.CharField(help_text='Contact number for inquiries', max_length=15)),
                ('image', models.ImageField(upload_to='property_images/')),
                ('description', models.TextField()),
                ('type', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bedrooms', models.IntegerField()),
                ('bathrooms', models.IntegerField()),
                ('kitchens', models.IntegerField()),
                ('facilities', models.TextField(help_text='Enter facilities separated by new lines')),
            ],
        ),
    ]
