# Generated by Django 5.1.6 on 2025-03-24 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_propertydetail_propertyimage_delete_property'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactUs',
        ),
    ]
